[package]
name = "iron_diesel_middleware"
version = "0.2.0"
authors = ["Darayus Nanavati <darayus.contact@gmail.com>"]

[dependencies]

iron = "0.5.1"
diesel = "0.15"

r2d2 = "0.7.3"
r2d2-diesel = {git = "https://github.com/jappeace/r2d2-diesel"}
